/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HuepfburgenRouteImport } from './routes/huepfburgen'
import { Route as IndexRouteImport } from './routes/index'

const HuepfburgenRoute = HuepfburgenRouteImport.update({
  id: '/huepfburgen',
  path: '/huepfburgen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/huepfburgen': typeof HuepfburgenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/huepfburgen': typeof HuepfburgenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/huepfburgen': typeof HuepfburgenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/huepfburgen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/huepfburgen'
  id: '__root__' | '/' | '/huepfburgen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HuepfburgenRoute: typeof HuepfburgenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/huepfburgen': {
      id: '/huepfburgen'
      path: '/huepfburgen'
      fullPath: '/huepfburgen'
      preLoaderRoute: typeof HuepfburgenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HuepfburgenRoute: HuepfburgenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
